<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1652336422410' stop='1652336428728'>
    <name>testSuite01</name>
    <title>testSuite01</title>
    <test-cases>
        <test-case start='1652336422410' status='broken' stop='1652336428727'>
            <name>tc01</name>
            <title>tc01</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
                <label name='feature' value='contact'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-101.0.4951.64'/>
            </parameters>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='4d037bd4-cfbb-40a3-9a54-88deacd0f97d-attachment.png' type='image/png' size='61871'/>
            </attachments>
            <failure>
                <message>intentional fail</message>
                <stack-trace>AssertionError: intentional fail
                    at Context.&lt;anonymous> (C:\Users\PradeepCR\Desktop\SEDT_32_WEBDRIVERIO\test\specs\tc_01.js:7:16)
                    at Context.executeAsync (C:\Users\PradeepCR\Desktop\SEDT_32_WEBDRIVERIO\node_modules\@wdio\utils\build\shim.js:331:27)
                    at Context.testFrameworkFnWrapper (C:\Users\PradeepCR\Desktop\SEDT_32_WEBDRIVERIO\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:51:32)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>